### ISSUE TITLE
Could not create NPC

### ISSUE THREAD

**Issue by Ratismal** [CitizensDev/Citizens#126]
When i tried to create a NPC, i typed:

/npc create Gerbality

i also tried:

/npc create Bob
/npc create Notch

well, you get the idea
in response, the server gives me:

Please report this error: [See console]
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V

(this is my homemade server)
When i checked the console, it gave me this message:

11:31 PM [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V 
11:31 PM [SEVERE]   at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35) 
11:31 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:46) 
11:31 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:89) 
11:31 PM [SEVERE]   at com.citizens.commands.commands.BasicCommands.create(BasicCommands.java:235) 
11:31 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
11:31 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
11:31 PM [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
11:31 PM [SEVERE]   at java.lang.reflect.Method.invoke(Unknown Source) 
11:31 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:518) 
11:31 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.execute(CommandsManager.java:404) 
11:31 PM [SEVERE]   at com.citizens.Citizens.onCommand(Citizens.java:196) 
11:31 PM [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39) 
11:31 PM [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) 
11:31 PM [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:347) 
11:31 PM [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756) 
11:31 PM [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721) 
11:31 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714) 
11:31 PM [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
11:31 PM [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
11:31 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:91) 
11:31 PM [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
11:31 PM [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464) 
11:31 PM [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374) 
11:31 PM [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417) 

Please someone help because I really want to use this plugin

**Comment by Ratismal** [comment]
Oh and i'm using the 1.7.3 craftbukkit, and it's patched for 1.8.1
i dont know what version it is, because i don't know how to find that out

**Comment by Coffeehedake** [comment]
In your server console, do /version. It may report the version number back.

**Comment by meiamone** [comment]
Same exact issue and error response here. Running Bukkit 1147? and mc1.8.1:

22:13:45 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1043
-g979f4e1-b1149jnks (MC: 1.8.1)
22:13:45 [INFO] This server is also sporting some funky dev build of Bukkit!

22:00:28 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldM
anager.<init>(Lnet/minecraft/server/WorldServer;)V
22:00:28 [SEVERE]       at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPC
Spawner.java:35)
22:00:28 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:46)
22:00:28 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:89)
22:00:28 [SEVERE]       at com.citizens.commands.commands.BasicCommands.create(B
asicCommands.java:235)
22:00:28 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
22:00:28 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
22:00:28 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
22:00:28 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
22:00:28 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.executeM
ethod(CommandsManager.java:518)
22:00:28 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.execute(
CommandsManager.java:404)
22:00:28 [SEVERE]       at com.citizens.Citizens.onCommand(Citizens.java:196)
22:00:28 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:39)
22:00:28 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:163)
22:00:28 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:353)
22:00:28 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:755)
22:00:28 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:720)
22:00:28 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:713)
22:00:28 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:3
3)
22:00:28 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
22:00:28 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:91)
22:00:28 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:108)
22:00:28 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:464)
22:00:28 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:374)
22:00:28 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:417)

**Comment by defaultsucks** [comment]
Could you please specify the version of citizens you're running?

**Comment by meiamone** [comment]
Yes, [INFO] [Citizens] version [1.0.9d](Odyssey) loaded

Also, now, everytime my server restarts there is this error message:

22:59:36 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet
/minecraft/server/WorldServer;)V
        at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35)

```
    at com.citizens.npcs.NPCManager.register(NPCManager.java:46)
    at com.citizens.Citizens.setupNPCs(Citizens.java:305)
    at com.citizens.Citizens.access$0(Citizens.java:286)
    at com.citizens.Citizens$1.run(Citizens.java:120)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
```

raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

Apparently the NPC-profiles.yml was written to when I attempted to create the NPC. Here is the contents:

'0':
    basic:
        look-when-close: 'true'
        location: LANDofNOT,1013.09375,25.0,807.28125,-274.0504,65.85003
        color: '15'
        name: Destati
        talk-when-close: 'false'

**Comment by defaultsucks** [comment]
No craftbukkit builds past #1092 work with citizens 1.0.9d. If you want you can try the latest dev build of citizens. That will surely work.

**Comment by meiamone** [comment]
Where can the dev version be downloaded?

**Comment by Coffeehedake** [comment]
http://ci.bukkit.org/job/dev-CraftBukkit/

**Comment by meiamone** [comment]
dev version of citizens, not craftbukkit. Thanks anyway Coffeehedake.
