### ISSUE TITLE
Citizen's Not working?

### ISSUE THREAD

**Issue by Date** [CitizensDev/Citizens#644]
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
19.01 12:45:52 [Server] SEVERE  at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
19.01 12:45:52 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:385)
19.01 12:45:52 [Server] SEVERE  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
19.01 12:45:52 [Server] SEVERE  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
19.01 12:45:52 [Server] SEVERE  at java.lang.reflect.Method.invoke(Method.java:601)
19.01 12:45:52 [Server] SEVERE  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.01 12:45:52 [Server] SEVERE  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
19.01 12:45:52 [Server] SEVERE  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
19.01 12:45:52 [Server] SEVERE  at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
19.01 12:45:52 [Server] SEVERE java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
19.01 12:45:37 [Multicraft] Date13 ran command Message of the Day
19.01 12:45:37 [Connect] User Date13, IP
19.01 12:44:50 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
19.01 12:44:50 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
19.01 12:44:50 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
19.01 12:44:50 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.Citizens$2.run(Citizens.java:134)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:284)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
19.01 12:44:50 [Server] INFO    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
19.01 12:44:50 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
19.01 12:44:50 [Server] WARNING Task of 'Citizens' generated an exception

**Comment by ghost** [comment]
Wow. Mine works. I can't create or delete...

**Comment by d00ba** [comment]
Citizens not working with bukkit 1.1 - Expect they will update after a recommended 1.1 bukkit release is available.

**Comment by Serverfrog** [comment]
Same issue as https://github.com/CitizensDev/Citizens/issues/646
