### ISSUE TITLE
Cannot Create NPC

### ISSUE THREAD

**Issue by Fisher900** [CitizensDev/Citizens#137]
I get this error when I attempt to use the /npc create [name] command:

java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)

To my knowledge I have installed everything correctly. I do not wish to have Permissions plugin on my server so it is not installed. Could that be the issue?

**Comment by aPunch** [comment]
Citizens 1.0.9d does not work with MC 1.8.x
