### ISSUE TITLE
Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by bastrian** [CitizensDev/Citizens#119]
Minecraft version; 1.8
Bukkit: git-Bukkit-0.0.0-1015-g56fa8f0-b1118jnks
Citizens: 1.0.9d
Info about the  bukkit version: 
Actual build is experimental, but the changes made under ItemInWorldManager will remain. 

Log Entry:
[WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
    at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:34)
    at com.citizens.npcs.NPCManager.register(NPCManager.java:55)
    at com.citizens.Citizens.setupNPCs(Citizens.java:321)
    at com.citizens.Citizens.access$0(Citizens.java:283)
    at com.citizens.Citizens$1.run(Citizens.java:119)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by aPunch** [comment]
Download a developmental build or wait until 1.1 is released. Citizens 1.0.9d only works with 1.7.x, Citizens 1.1 will work with 1.8.x.
