### ISSUE TITLE
[WARNING] Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by nexitem** [CitizensDev/Citizens#457]
Using Latest Developer version of Bukkit, 07:16:02 [INFO] This server is running Craftbukkit version git-Bukkit-1.8.1-R4-104-g4de7992-b1575jnks (MC: 1.0.1) (Implementing API version 1.0.0-R1-SNAPSHOT)

This is the only thing thats stopping me from using the newest bukkit versions... cause citizens works fine with older versions on 1.0 Please fix at least this one bug for us so we can update :(

07:14:40 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/Packet17
        at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)
        at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
07:14:40 [INFO] ControllerBlock: Loaded v4 data - 1 ControllerBlocks loaded

**Comment by Fureniku** [comment]
What older versions work with it, and whats the issue with using those versions until citizens is updated?

**Comment by np98765** [comment]
I have the same issue.  VERY ANNOYING.  NPC's cannot be used at all

**Comment by nexitem** [comment]
Oh sorry for late response.

The last version where it works for me is #1529. And the issue with using those old versions is that i would really love to have the latest bug fixes :) thats it.

I mean comon, Who would not like to fix stuff like:

Fixed corrupt mob spawners crashing on load - this fixes BUKKIT-69, BUKKIT-

Fixed issues with Ender Pearls. This fixes BUKKIT-248 and BUKKIT-264.

Fixed (Bukkit multiworld) maps as described in BUKKIT-142.

Fixed NPE in ServerConfigurationManager when sometimes attempting to flee the End 

Fixed issues in our handling of The End as per BUKKIT-11.

Teach MinecraftServer how to handle Remote Console commands. 

Fixed exp resetting upon teleporting cross-world (fixes BUKKIT-46. Again.)

fix NPE issue with CB inventory 

Make the EnderDragon respect experience drop set in death event

Fixed exploit with Ender Pearls, and made them perform a damage event. This fixes BUKKIT-38 

Implemented 1.0.1 fixes. This fixes BUKKIT-3, BUKKIT-39, BUKKIT-150 

cleanup of projectiles

**Comment by nexitem** [comment]
craftbukkit-1.0.1-R1 --- Same problem ( With latest builds from citizens ) ?

**Comment by fullwall** [comment]
Download 1.1.3 Citizens.
