### ISSUE TITLE
DOES NOT WORK WITH 1.8.1!!

### ISSUE THREAD

**Issue by camcade** [CitizensDev/Citizens#145]
Hello,
I have tried numerous times,but I cannot get this plugin to run with the new 1.8.1 version of minecraft!

**Comment by kris76** [comment]
What is your version of Craftbukkit ? Post the log error...

**Comment by MikeGold** [comment]
I've got the simmilar problem. Simply when I turn on the server, it shows the error in citizens and does not load my old citizens. So I thought that I could let it create it all from scratch and then I would add my Citizens. The problem is that if it recreates files from scratch it works ok until I try to create NPC in game. 

Bukkit Build: 1185 (MC: 1.8.1)
Citizens ver. 1.0.9d

Error when trying to create NPC:

18:35:52 [INFO] [Spout] Successfully authenticated mikandesu's Spoutcraft client
. Running client version: 1.0.6.449
18:36:04 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldM
anager.<init>(Lnet/minecraft/server/WorldServer;)V
18:36:04 [SEVERE]       at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPC
Spawner.java:35)
18:36:04 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:46)
18:36:04 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:89)
18:36:04 [SEVERE]       at com.citizens.commands.commands.BasicCommands.create(B
asicCommands.java:235)
18:36:04 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
18:36:04 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
18:36:04 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
18:36:04 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
18:36:04 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.executeM
ethod(CommandsManager.java:518)
18:36:04 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.execute(
CommandsManager.java:404)
18:36:04 [SEVERE]       at com.citizens.Citizens.onCommand(Citizens.java:196)
18:36:04 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:39)
18:36:04 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:163)
18:36:04 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:353)
18:36:04 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:756)
18:36:04 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:721)
18:36:04 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:714)
18:36:04 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:3
3)
18:36:04 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
18:36:04 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:92)
18:36:04 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetSe
rverHandler.java:500)
18:36:04 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:108)
18:36:04 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:464)
18:36:04 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:374)
18:36:04 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:417)

Error when I try to use my previous npc npc-profiles.yml

D:\instalki.craftbukkit>"C:\Program Files (x86)\Java\jre6\bin\java.exe" -Xincgc
 -Xmx1G -jar -jar D:\instalki.craftbukkit\craftbukkit-0.0.1-SNAPSHOT.jar
161 recipes
17 achievements
18:46:13 [INFO] Starting minecraft server version Beta 1.8.1
18:46:13 [INFO] Loading properties
18:46:13 [INFO] Starting Minecraft server on *:25565
18:46:13 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067
-g6301507-b1185jnks (MC: 1.8.1)
18:46:14 [INFO] [Permissions](Yeti) was initialized.
18:46:14 [INFO] [Permissions] version [3.1.6](Yeti)  loaded
18:46:14 [INFO] Spout 1.0.6.382 has been initialized
18:46:14 [INFO] Preparing level "Mikania"
18:46:14 [INFO] Default game type: 0
18:46:14 [INFO] Preparing start region for level 0 (Seed: 6443500349175639597)
18:46:15 [INFO] Preparing spawn area: 44%
18:46:15 [INFO] Preparing start region for level 1 (Seed: 6443500349175639597)
18:46:16 [INFO] Preparing spawn area: 40%
18:46:17 [INFO] [*] DirectBank enabled.
18:46:17 [INFO] Preparing start region for level 2 (Seed: 6443500349175639597)
18:46:18 [INFO] Preparing spawn area for Mikania_nightmare, 81%
18:46:18 [INFO] Preparing start region for level 3 (Seed: -6399648701760404980)
18:46:19 [INFO] Preparing spawn area for Mikania_skylands, 97%
18:46:19 [INFO] DreamLand version 2.4 is enabled!
18:46:19 [INFO] Loaded Essentials build 2.5.7 by [Zenexer, ementalo, Aelux, Bret
tflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
18:46:19 [INFO] [Essentials] Payment method found (iConomy version: 5)
18:46:19 [INFO] Loaded EssentialsChat build 2.5.7 by essentials team
18:46:19 [INFO] Loaded EssentialsGeoIP build 2.5.7 by essentials team
18:46:19 [INFO] This product includes GeoLite data created by MaxMind, available
 from http://www.maxmind.com/.
18:46:19 [INFO] Loaded EssentialsSpawn build 2.5.7 by essentials team
18:46:19 [INFO] [iConomy] Logging is currently disabled.
18:46:19 [INFO] [iConomy] v5.0 (Eruanna) loaded.
18:46:19 [INFO] [iConomy] Developed by: [Nijikokun]
18:46:19 [INFO] [iConomy] hooked into Permissions.
18:46:19 [INFO] MoneyDrop is up and running!
18:46:19 [INFO] [MoneyDrop] Economy found. Money pickup enabled.
18:46:19 [INFO] [NPC-Quester]: Setting up config files
18:46:19 [INFO] [NPC-Quester]: Config file found!
18:46:19 [INFO] [NPC-Quester]: Players file found!
18:46:19 [INFO] [NPC-Quester]: Permissions detected
18:46:19 [INFO] [NPC-Quester]: Random branch is empty, ignoring.
18:46:19 [INFO] [NPC-Quester]: Players branch is empty, ignoring.
18:46:19 [INFO] [NPC-Quester]: Players completed branch is empty, ignoring.
18:46:19 [INFO] [NPC-Quester]: enabled
18:46:19 [INFO] [PersonalChest] version 1.0.1 loading...
18:46:19 [INFO] [PersonalChest] version 1.0.1 is enabled with permissions!
18:46:20 [INFO] [uQuest] Loaded with Flatfile!
18:46:20 [INFO] [uQuest] v1.5 enabled! With 53 quests loaded!
18:46:20 [INFO] [VanishNoPickup] 1.9.12 enabled.
18:46:20 [INFO] [Citizens] Loaded 0 quests.
18:46:20 [INFO] [Citizens] Permissions enabled.
18:46:20 [INFO] [Citizens] version [1.0.9d](Odyssey) loaded
18:46:20 [INFO] [Citizens] Payment method found (iConomy version: 5)
18:46:20 [INFO] [mcMMO] Permissions version 3.1.6 found, using Permissions.
18:46:20 [INFO] Loading Config File...
18:46:21 [INFO] [mcMMO] Permissions version 3.1.6 found, using Permissions.
18:46:21 [INFO] mcMMO version 1.1.11 is enabled!
18:46:21 [INFO] [OddItem] 0.7.3.1 enabled
18:46:21 [INFO] [OddItem] Using RefinedSoundEx for suggestions.
18:46:21 [INFO] [OddItem] Group samplegroup added: [greenwool, ironblock:2, diod
e]
18:46:21 [INFO] [OddItem] 851 aliases loaded.
18:46:21 [INFO] [MyWolf] Permissions integration enabled!
18:46:21 [INFO] [MyWolf] 1 wolf/wolves loaded
18:46:21 [INFO] [MyWolf] version 0.5.0 ENABLED
18:46:21 [INFO] Server permissions file permissions.yml is empty, ignoring it
18:46:21 [INFO] Done (0.759s)! For help, type "help" or "?"
18:46:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet
/minecraft/server/WorldServer;)V
        at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35)

```
    at com.citizens.npcs.NPCManager.register(NPCManager.java:46)
    at com.citizens.Citizens.setupNPCs(Citizens.java:305)
    at com.citizens.Citizens.access$0(Citizens.java:286)
    at com.citizens.Citizens$1.run(Citizens.java:120)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
```

raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
18:46:25 [INFO] [uQuest] Successfully linked with iConomy.
18:46:25 [INFO] [uQuest] Successfully linked with Permissions.
18:46:25 [INFO] [uQuest] Successfully linked with Essentials.
18:46:27 [INFO] [NPC-Quester] Total quests: 53

**Comment by defaultsucks** [comment]
Citizens 1.0.9d doesn't work with 1.8 craftbukkit builds. The newest dev builds of citizens however do work. 

http://jenkins.citizensnpcs.net:81/job/Citizens/

**Comment by MikeGold** [comment]
I'm trying to avoid new version of citizens because I would have to
remove permissions and replace them with something else which I would
have to learn from scratch.

2011/9/24 defaultsucks
reply@reply.github.com:

> Citizens 1.0.9d doesn't work with 1.8 craftbukkit builds. The newest dev builds of citizens however do work.
> 
> http://jenkins.citizensnpcs.net:81/job/Citizens/
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CitizensDev/Citizens/issues/145#issuecomment-2187656

## 

---

Never argue with an idiot. First he will bring you down to his level
then he will beat you with experience.

**Comment by defaultsucks** [comment]
Well it's either that, downgrading your server or removing citizens.

**Comment by MikeGold** [comment]
Not everyone of us is a programmer. So I'd only like to ask you which
permission plugin would let me convert the least painfull way with
keeping citizens on my server?

2011/9/24 defaultsucks
reply@reply.github.com:

> Well it's either that, downgrading your server or removing citizens.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CitizensDev/Citizens/issues/145#issuecomment-2187686

## 

---

Never argue with an idiot. First he will bring you down to his level
then he will beat you with experience.

**Comment by kris76** [comment]
Consider using PermissionsBukkit or another plugin compatible with SuperPerms. It will certainly become a standard.

**Comment by Malific** [comment]
I would suggest PermissionsEX.

You use the same way you use permissions, and it auto links it for superperm plugins.

**Comment by MikeGold** [comment]
Ok. I'm about to give up. I've tried PermissionsEX, and everything is
ok, but when I try to use my old NPC profiles, I'm flooded with so
many errors that after a few minutes I gave up. Now, if I try to start
from scratch, and created my first npc and toggled him to trader it
worked ok, but when I try to click it (either right or left) nothing
happens in game but on server I get some errors.

Here is the log of my server starting, then I'm running a client and
trying to click npc and here comes the bug.

D:\instalki.craftbukkit>"C:\Program Files (x86)\Java\jre6\bin\java.exe" -Xincgc
 -Xmx1G -jar -jar D:\instalki.craftbukkit\craftbukkit-0.0.1-SNAPSHOT.jar
161 recipes
17 achievements
19:28:44 [INFO] Starting minecraft server version Beta 1.8.1
19:28:44 [INFO] Loading properties
19:28:44 [INFO] Starting Minecraft server on *:25565
19:28:45 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067
-g6301507-b1185jnks (MC: 1.8.1)
19:28:45 [INFO] [PermissionsEx] sql backend registered!
19:28:45 [INFO] [PermissionsEx] file backend registered!
19:28:45 [INFO] [PermissionsEx] PermissionEx plugin initialized.
19:28:45 [INFO] MLog clients using java 1.4+ standard logging.
19:28:45 [INFO] [PermissionsEx] Initializing file backend
19:28:45 [INFO] Spout 1.0.6.382 has been initialized
19:28:45 [INFO] Preparing level "Mikania"
19:28:45 [INFO] Default game type: 0
19:28:46 [INFO] Preparing start region for level 0 (Seed: 6443500349175639597)
19:28:47 [INFO] Preparing spawn area: 57%
19:28:47 [INFO] Preparing start region for level 1 (Seed: 6443500349175639597)
19:28:48 [INFO] Preparing spawn area: 60%
19:28:48 [INFO] [*] DirectBank enabled.
19:28:48 [INFO] Preparing start region for level 2 (Seed: 6443500349175639597)
19:28:49 [INFO] Preparing spawn area for Mikania_nightmare, 85%
19:28:49 [INFO] Preparing start region for level 3 (Seed: -6399648701760404980)
19:28:50 [INFO] Preparing spawn area for Mikania_skylands, 97%
19:28:50 [INFO] DreamLand version 2.4 is enabled!
19:28:50 [WARNING] Version mismatch! Please update EssentialsGeoIP to the same v
ersion.
19:28:50 [INFO] Loaded Essentials build 2.6.1 by: Zenexer, ementalo, Aelux, Bret
tflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
19:28:50 [INFO] Essentials: Using superperms based permissions.
19:28:50 [INFO] [Essentials] Payment method found (iConomy version: 5)
19:28:50 [INFO] Loaded EssentialsChat build 2.6.1 by: essentials team
19:28:50 [WARNING] Version mismatch! Please update all Essentials jars to the sa
me version.
19:28:50 [INFO] Loaded EssentialsGeoIP build 2.5.7 by: essentials team
19:28:50 [INFO] This product includes GeoLite data created by MaxMind, available
 from http://www.maxmind.com/.
19:28:51 [INFO] Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? tr
ue; trace: 10]
19:28:51 [INFO] Loaded EssentialsProtect build 2.6.1 by: essentials team
19:28:51 [INFO] Loaded EssentialsSpawn build 2.6.1 by: essentials team
19:28:53 [INFO] [iConomy] Logging is currently disabled.
19:28:53 [INFO] [iConomy] v5.0 (Eruanna) loaded.
19:28:53 [INFO] [iConomy] Developed by: [Nijikokun]
19:28:53 [INFO] MoneyDrop is up and running!
19:28:53 [INFO] [MoneyDrop] Economy found. Money pickup enabled.
19:28:53 [INFO] [NPC-Quester]: Setting up config files
19:28:53 [INFO] [NPC-Quester]: Config file found!
19:28:53 [INFO] [NPC-Quester]: Players file found!
19:28:53 [INFO] [NPC-Quester]: Permissions not detected
19:28:53 [INFO] [NPC-Quester]: Random branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: Players branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: Players completed branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: enabled
19:28:53 [INFO] [PermissionsEx] Superperms support enabled.
19:28:53 [INFO] [PermissionsEx] v1.14 enabled
19:28:53 [INFO] Essentials: Using PermissionsEx based permissions.
19:28:53 [INFO] [PersonalChest] version 1.0.1 loading...
19:28:53 [INFO] [PersonalChest] version 1.0.1 is enabled without permissions!
19:28:53 [INFO] [uQuest] Loaded with Flatfile!
19:28:53 [INFO] [uQuest] v1.5 enabled! With 53 quests loaded!
19:28:53 [INFO] [VanishNoPickup] Permissions not detected.
19:28:53 [INFO] [VanishNoPickup] 1.9.12 enabled.
19:28:53 [INFO] [mcMMO] PermissionsEx found, using PermissionsEx.
19:28:53 [INFO] Loading Config File...
19:28:55 [INFO] mcMMO version 1.1.11 is enabled!
19:28:55 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
19:28:55 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
19:28:55 [INFO] [Citizens] version [devBuild-205] loaded.
19:28:55 [INFO] [Citizens] Economy plugin found (iConomy v5)
19:28:55 [INFO] [MyWolf] PermissionsEX integration enabled!
19:28:55 [INFO] [MyWolf] 1 wolf/wolves loaded
19:28:55 [INFO] [MyWolf] version 0.5.0 ENABLED
19:28:55 [INFO] [OddItem] 0.7.3.1 enabled
19:28:55 [INFO] [OddItem] Using RefinedSoundEx for suggestions.
19:28:55 [INFO] [OddItem] Group samplegroup added: [greenwool, ironblock:2, diod
e]
19:28:55 [INFO] [OddItem] 851 aliases loaded.
19:28:55 [INFO] Done (0.979s)! For help, type "help" or "?"
19:28:55 [INFO] [Citizens] Loaded 1 NPCs.
19:28:55 [INFO] [Citizens] Loaded 0 quests.
19:28:55 [INFO] New max size: 484
19:28:55 [INFO] New max size: 784
19:28:58 [INFO] [uQuest] Successfully linked with iConomy.
19:28:58 [INFO] [uQuest] Successfully linked with Essentials.
19:28:58 [SEVERE] [uQuest] Permissions is not loaded. Turning Permissions suppor
t off.
19:29:01 [INFO] mikandesu [/192.168.1.2:60400] logged in with entity id 395 at (
[Mikania] 95.9115627147039, 28.5, -69.35114815649155)
19:29:02 [INFO] Reading data
19:29:02 [INFO] [Spout] Successfully authenticated mikandesu's Spoutcraft client
. Running client version: 1.0.6.449
19:29:02 [INFO] [NPC-Quester] Total quests: 53
19:29:15 [SEVERE] Could not pass event PLAYER_INTERACT_ENTITY to NPCQuester
java.lang.NoClassDefFoundError: com/citizens/npcs/NPCManager
        at randy.npcq.npcqEntityListener.onPlayerInteractEntity(npcqEntityListen
er.java:55)
        at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.j
ava:321)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:338)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:902)
        at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
:500)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: com.citizens.npcs.NPCManager
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more
